import uuid
from typing import List

from app.vectorstore.base import VectorStore
from app.rag.types import RAGResponse


class RAGPipeline:
    def __init__(self, vectorstore):
        self.vectorstore = vectorstore

    def run(self, query: str, request_id: str):
        # Retrieve documents
        sources = self.vectorstore.search(query, top_k=3)

        # Fake / simple answer generation for now
        answer = "This is a placeholder answer generated by Secure RAG v2."

        return {
            "answer": answer,
            "sources": sources,
            "security_flags": {},
            "request_id": request_id,
        }
